### ISSUE TITLE
What font are you using?

### ISSUE THREAD

**Issue by spynygdypolytoxin** [carykh/WordleEdit#2]
Hey, just wondering what the font used in the image below is called.
![image](https://user-images.githubusercontent.com/94858677/186697276-c1c6a50a-f51e-43e5-b9b4-4060ed1edad0.png)
cool ty

**Comment by Angel-IG** [comment]
It's the same as the one he used in his Abacaba Graphing Tutorial, so according to [this](https://youtu.be/dgqXJeCUNyA?t=531) it's `Jygquif-48`. However, I haven't found that name anywhere. Good luck, that was all the info I could give you :P

**Comment by carykh** [comment]
My brother created a variation of the font "Interstate", which is used on US Highway signs, and called it "Jygquif" in 2015. I think if you just google "Interstate", it should show up!
